services:
  postgres:
    image: postgres:15
    container_name: postgres-getouthole
    restart: always
    environment:
      POSTGRES_DB: getouthole
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-getouthole
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@getouthole.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

