services:
  postgres:
    image: postgres:15
    container_name: postgres-getouthole
    restart: always
    environment:
      POSTGRES_DB: getouthole
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: