spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/getouthole
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

jwt:
  secret: ${SECRET_TOKEN}
  expiration: 86400000 # 1 dia em milissegundos

pluggy:
  client-id: ${PLUGGY_CLIENT_ID}
  client-secret: ${PLUGGY_CLIENT_SECRET}